### ISSUE TITLE
CI: Notify on ms Teams about the merge 

### ISSUE THREAD

**Issue by DicksonKuan** [MST619/Devops-Team2#122]

**Comment by DicksonKuan** [comment]
Hey @MST619 I would like to request your help to add the Team's webhook secrets into GitHub thanks.

**Comment by MST619** [comment]
Hi @DicksonKuan Will get on it.

**Comment by DicksonKuan** [comment]
Hi @MST619, I have also added one more CI to auto-tag each push to the main branch. 

Would like your assistance to add the GITHUB secrets thanks !

**Comment by MST619** [comment]
Noted@DicksonKuan. I'll take a closer look at it later.
