### ISSUE TITLE
7. Playing game

### ISSUE THREAD

**Issue by DicksonKuan** [MST619/Devops-Team2#8]
- [ ] Display map layout 
- [ ] Build building according to user's input
- [ ] Display remaining buildings
- [ ] Calculate total score
- [ ] Save Game
- [ ] Exit to main menu

**Comment by 3thannn** [comment]
Good Morning @JeremiahLDX00 @isaiahlowjung, I have come up with a few test cases for the display game menu and game grid,  as well as taken down some notes and logic for coding out these said functions. Please use the test cases thinking word document, for your reference. 

@DicksonKuan @MST619 Please take note of this, and schedule a deadline/soft due date for them.

Thanks everyone
