### ISSUE TITLE
Display game grid size

### ISSUE THREAD

**Issue by DicksonKuan** [MST619/Devops-Team2#87]
To display the unique game grid size according to the user

new requirements:
- Ensure that the user’s input for both y and x-axis size for game grid size selection is recorded in the system correctly
- Ensure that the game grid nested list to display in UI is correct

Progress
- [x] Unit test case 
- [x] Unit test code
- [x] Code

**Comment by DicksonKuan** [comment]
Hi @3thannn can I get your approval that this issue has been done thanks.

**Comment by 3thannn** [comment]
Looked through it, so far ok, might want to look into further refine our coding practices by instead using 'data' for all nested list items, as currently our axis list is just one long string. Will communicate with @isaiahlowjung on reverting it to the better way. But apart from that LGTM!, unit test passes and covers what's needed to be tested! Thanks @isaiahlowjung

**Comment by MST619** [comment]
Closing this issue for milestone two. Thanks!

**Comment by MST619** [comment]
@isaiahlowjung How's the progress? I would like to close this issue for the closure of milestone 2.

**Comment by isaiahlowjung** [comment]
Hi @MST619, the feature together with the tests work and there is validation for maximum grid size, but there is no input validation yet. I think that it's fine to close, I'll work on the validation once the rest of the core features are there. Thanks!

**Comment by MST619** [comment]
Noted with thanks! @isaiahlowjung I'll close the issue now.
