### ISSUE TITLE
Define map size #2.2.1 

### ISSUE THREAD

**Issue by DicksonKuan** [MST619/Devops-Team2#93]
- [x] Unit test code
- [x] Code

**Comment by DicksonKuan** [comment]
Hi @MST619 would need your help to test if my unit test code thanks

**Comment by MST619** [comment]
Alright! @DicksonKuan

**Comment by MST619** [comment]
@DicksonKuan Apologies for the delay in testing. I just finished testing and the defining the map size works great!
